// frontend/src/components/icons.tsx

import { LucideProps } from "lucide-react"
import {
  FileText as FileTextIcon,
  HardDrive as HardDriveIcon,
  MoreHorizontal as MoreHorizontalIcon,
  Mail as MailIcon,
  Lock as LockIcon,
  Loader2 as Loader2Icon,
  LogIn as LogInIcon,
  User as UserIcon,
  UserPlus as UserPlusIcon,
  Github as GithubIcon,
  Chrome as ChromeIcon,
  ChevronDown as ChevronDownIcon,
  Menu as MenuIcon,
  X as XIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Laptop as LaptopIcon,
  Plus as PlusIcon,
  Trash2 as Trash2Icon,
  Edit2 as Edit2Icon,
  Save as SaveIcon,
  AlertCircle as AlertCircleIcon,
  CheckCircle2 as CheckCircle2Icon,
  XCircle as XCircleIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  Home as HomeIcon,
  File as FileIcon,
  Folder as FolderIcon,
  Image as ImageIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Share2 as Share2Icon,
  Copy as CopyIcon,
  ExternalLink as ExternalLinkIcon,
  Link as LinkIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  Tag as TagIcon,
  Filter as FilterIcon,
  Sliders as SlidersIcon,
  Grid as GridIcon,
  List as ListIcon,
  LayoutDashboard as LayoutDashboardIcon,
  BarChart2 as BarChart2Icon,
  PieChart as PieChartIcon,
  LineChart as LineChartIcon,
  Code as CodeIcon,
  Terminal as TerminalIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Cpu as CpuIcon,
  HardDrive as HardDrive2Icon,
  Cloud as CloudIcon,
  CloudOff as CloudOffIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  MessageSquare as MessageSquareIcon,
  Inbox as InboxIcon,
  Send as SendIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Heart as HeartIcon,
  Star as StarIcon,
  Flag as FlagIcon,
  Bookmark as BookmarkIcon,
  BookOpen as BookOpenIcon,
  Book as BookIcon,
  FilePlus as FilePlusIcon,
  FileMinus as FileMinusIcon,
  FileCheck as FileCheckIcon,
  FileX as FileXIcon,
  FileSearch as FileSearchIcon,
  FileCode as FileCodeIcon,
  FileImage as FileImageIcon,
  FileAudio as FileAudioIcon,
  FileVideo as FileVideoIcon,
  FileArchive as FileArchiveIcon,
  FileSpreadsheet as FileSpreadsheetIcon,
  FileJson as FileJsonIcon,
} from "lucide-react";

export const Icons = {
  spinner: Loader2Icon,
  google: (props: LucideProps) => (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M21.8,10.5H12v4h5.6c-0.3,1.6-1.5,2.8-3.1,3.3c-0.7,0.2-1.4,0.2-2.1,0c-0.6-0.2-1.2-0.5-1.7-0.9c-0.5-0.4-0.9-0.9-1.2-1.5c-0.3-0.6-0.5-1.2-0.5-1.9c0-0.7,0.2-1.3,0.5-1.9c0.3-0.6,0.7-1.1,1.2-1.5c0.5-0.4,1.1-0.7,1.7-0.9c0.7-0.2,1.4-0.2,2.1,0c0.6,0.2,1.2,0.5,1.7,0.9L18.4,6.6c-0.9-0.8-2-1.3-3.2-1.6c-1.2-0.3-2.4-0.2-3.5,0.1c-1.1,0.3-2.1,0.9-2.9,1.7c-0.8,0.8-1.4,1.8-1.8,2.9c-0.4,1.1-0.5,2.3-0.3,3.5c0.2,1.2,0.8,2.3,1.6,3.2c0.8,0.9,1.8,1.5,3,1.9c1.1,0.4,2.3,0.5,3.5,0.3c1.2-0.2,2.3-0.8,3.2-1.6c0.9-0.8,1.5-1.8,1.9-3c0.4-1.1,0.5-2.3,0.3-3.5c-0.2-1.2-0.8-2.3-1.6-3.2L21.8,10.5z" />
    </svg>
  ),
  fileText: FileTextIcon,
  hardDrive: HardDriveIcon,
  moreHorizontal: MoreHorizontalIcon,
  mail: MailIcon,
  lock: LockIcon,
  loader2: Loader2Icon,
  logIn: LogInIcon,
  user: UserIcon,
  userPlus: UserPlusIcon,
  github: GithubIcon,
  chevronDown: ChevronDownIcon,
  menu: MenuIcon,
  x: XIcon,
  sun: SunIcon,
  moon: MoonIcon,
  laptop: LaptopIcon,
  plus: PlusIcon,
  trash2: Trash2Icon,
  edit2: Edit2Icon,
  save: SaveIcon,
  alertCircle: AlertCircleIcon,
  checkCircle2: CheckCircle2Icon,
  xCircle: XCircleIcon,
  chevronRight: ChevronRightIcon,
  chevronLeft: ChevronLeftIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  logOut: LogOutIcon,
  home: HomeIcon,
  file: FileIcon,
  folder: FolderIcon,
  image: ImageIcon,
  upload: UploadIcon,
  download: DownloadIcon,
  share2: Share2Icon,
  copy: CopyIcon,
  externalLink: ExternalLinkIcon,
  link: LinkIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  calendar: CalendarIcon,
  clock: ClockIcon,
  tag: TagIcon,
  filter: FilterIcon,
  sliders: SlidersIcon,
  grid: GridIcon,
  list: ListIcon,
  layoutDashboard: LayoutDashboardIcon,
  barChart2: BarChart2Icon,
  pieChart: PieChartIcon,
  lineChart: LineChartIcon,
  code: CodeIcon,
  terminal: TerminalIcon,
  database: DatabaseIcon,
  server: ServerIcon,
  cpu: CpuIcon,
  hardDrive2: HardDrive2Icon,
  cloud: CloudIcon,
  cloudOff: CloudOffIcon,
  wifi: WifiIcon,
  wifiOff: WifiOffIcon,
  bell: BellIcon,
  bellOff: BellOffIcon,
  messageSquare: MessageSquareIcon,
  inbox: InboxIcon,
  send: SendIcon,
  thumbsUp: ThumbsUpIcon,
  thumbsDown: ThumbsDownIcon,
  heart: HeartIcon,
  star: StarIcon,
  flag: FlagIcon,
  bookmark: BookmarkIcon,
  bookOpen: BookOpenIcon,
  book: BookIcon,
  filePlus: FilePlusIcon,
  fileMinus: FileMinusIcon,
  fileCheck: FileCheckIcon,
  fileX: FileXIcon,
  fileSearch: FileSearchIcon,
  fileCode: FileCodeIcon,
  fileImage: FileImageIcon,
  fileAudio: FileAudioIcon,
  fileVideo: FileVideoIcon,
  fileArchive: FileArchiveIcon,
  fileSpreadsheet: FileSpreadsheetIcon,
  fileJson: FileJsonIcon,
}
